### ISSUE TITLE
README mentions Arduino 1.5.6-r2 as the base, but provides a link to 1.5.5-r2

### ISSUE THREAD

**Issue by codyps** [flutterwireless/ArduinoCodebase#1]
> Arduino IDE version 1.5.6-r2. To see which changes have been made, simply run a diff of the files in this folder with the unmodified repository. A copy of that is available here: www.flutterwireless.com/files/Arduino-1.5.5-r2.zip

Which is correct?
Is the .zip file misnamed?

**Comment by sequoia-hope** [comment]
Derp, no the zip is correct. I originally thought it was 1.5.6-r2 but I realized that was incorrect and didn't change the text. Fixing now...
